### ISSUE TITLE
not automatically creating gseen.dat

### ISSUE THREAD

**Issue by Syerween** [cycoslave/gseen.mod#4]
When a newly configured eggdrop, it will not automatically create the gseen.dat. 
From what I know from the previous version it will auto create the file.

**Comment by cycoslave** [comment]
Are you still having issues with the gseen.dat file?

**Comment by Syerween** [comment]
I am good. All of a sudden i can see now the gseen.dat file. It's just weird that 3 versions I used 1.6.21/1.9.5/1.10.0 it did not auto create. Or will it just take time for that file to be created once there's data?

**Comment by cycoslave** [comment]
this version of gseen would work better with the 1.9.x eggdrop version.
the changes I did were mostly to adapt the module to the new language style in 1.9.x that was not accounted for.

for eggdrop 1.6.x or 1.10.x, I would use the official versions from eggheads.org

**Comment by cycoslave** [comment]
but to comment on the actual issue, I think the database file only gets created once the bot sees an action to add names to the data file.

so yes, it does take a some time before the data file gets first created :)
